version: '3'

services:
  mongodb:
    image: mongo:4.0
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.14
    environment:
      - discovery.type=single-node
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
      args:
        WEBAPP_GIT: https://github.com/biothings/biothings_studio.git
        GIT_CHECKOUT: master
    ports:
      - "8080:80"
  biothings:
    build:
      context: .
      dockerfile: Dockerfile.biothings
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
        PYTHON_VERSION: 3.6
        BIOTHINGS_VERSION: 0.9.1
        API_GIT: https://github.com/biothings/myvariant.info.git
        API_NAME: myvariant.info
    init: true
    depends_on:
      - "mongodb"
      - "elasticsearch"
    volumes:
      # Forwards the local Docker socket to the container.
      # This is required because the docker extension in VSC needs it.
      # - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/home/vscode/biothings.api

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
