version: '3'

services:
  mongodb:
    image: mongo:4.0
    ports:
      - "127.0.0.1:27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.14
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:9200:9200"
  biothings:
    build:
      context: ..
      dockerfile: docker/biothings/Dockerfile
    ports:
      - "127.0.0.1:7080:7080"
      - "127.0.0.1:7022:7022"
