version: '3'

services:
  mongodb:
    image: mongo:4.0
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.14
    environment:
      - discovery.type=single-node
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
      args:
        WEBAPP_GIT: https://github.com/biothings/biothings_studio.git
        GIT_CHECKOUT: master
    ports:
      - "127.0.0.1:8080:80"
  biothings:
    build:
      context: biothings
      dockerfile: Dockerfile
    init: true
    depends_on:
      - "mongodb"
      - "elasticsearch"
      - "webapp"
    volumes:
      # Forwards the local Docker socket to the container.
      # This is required because the docker extension in VSC needs it.
      # - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/biothings

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - "127.0.0.1:7080:7080"
      - "127.0.0.1:7022:7022"
